### ISSUE TITLE
Holmer Terra Varriant 435 and 585 not working

### ISSUE THREAD

**Issue by Merrlin** [stijnwop/manureSystem#13]
Hi Wopster,

I've found an Issue with the two Holmer Vehicles. I cannot fill them. I'm not able to connect the Hoses on the right side of the Vehicle.
The same problem appears with the Dock arm. If i put it on the Funnel of Kotte TSA 30000 or Kotte FRC, nothing happens when i turn on the Pump.
I've used the ModVersion provided via ModHub.
[log.txt](https://github.com/stijnwop/manureSystem/files/4320723/log.txt)

Greetings Daniel

P.S. I've found an Issue with the Slurry Lagoon. The Fence beside the Mixer has no Collision. Where schould I report this?

**Comment by stijnwop** [comment]
Euhm what holmer are you exactly using?

You understand that you need the one from Giants? Modded versions of the Holmer won't work without being prepared.

**Comment by Merrlin** [comment]
Jipp, both From the Holmer DLC. The one with fixed tank and the one with the attached tank are both not working. Or at least I'm too noob to get them working.
Attaching hoses or connecting equipment like FRC or Zunhammer trailed Barrel works perfectly fine.
I've tried it on my testsave with no mods exept the Class ones, easy development control and Courseplay.

**Comment by Merrlin** [comment]
Short addition: in the keyboard menu the commands for filling direction (Y) and turn on pump(R) are shown properly. So I think the mod is injected correct.

**Comment by MrMarcel5** [comment]
Which DLC version do you have? From the Giants‘s ModHub or through Steam?

**Comment by Merrlin** [comment]
It's the stream version. As shown in log, it's version 1.0.1.0

**Comment by dziuch** [comment]
I tried to reproduce it but the only issue I have is when connecting the Terra Variant 435 with other tanker/lagoon the pumping cannot be started - there's no option in the F1 menu and hitting the key does nothing. Other than that everything else works correctly.

@Merrlin are you sure you're connecting the normal hose and not the extension?

**Comment by Merrlin** [comment]
Of course I connect the right one. I've tried with both of them in any direction.
Neither the the connector between the tires nor the docking arm works

**Comment by ddewar** [comment]
Hey, just noting I am also experiencing this issue. Can't get hoses to connect to the Holmer DLC equipment, or use any of the fill arms or funnels.

**Comment by stijnwop** [comment]
Pushed a fix according this, please test!

**Comment by ddewar** [comment]
Any Github release coming up? Or should we do a pull and run the zip command or zip manually.

**Comment by stijnwop** [comment]
Release will be done when I fixed most of the stuff and prepare a new update.

So would say pull the GitHub version and zip it manually as the zip.cmd will require you to have the 7zip application available in your path variable.

**Comment by dziuch** [comment]
Well, I don't know about Merrlin but it fixed my issue.

**Comment by ddewar** [comment]
Can also confirm, looks like the hoses work. Still seeing some oddities with the commands not showing up for the 435, but I was able to get it to work for the most part.

**Comment by stijnwop** [comment]
2 confirms.. @Merrlin how about you?

**Comment by Merrlin** [comment]
Hey sorry hadn't dime for testring until now.
There are good news and bad news.
The good news: The problems with the holmer are fixed.
The bad news: The hoses can't be coupled together. But for this one i open an new issue so this can be closed. 
I used commit f71705f
