### ISSUE TITLE
Mod conflict with Contractor mod

### ISSUE THREAD

**Issue by AC2500S** [stijnwop/manureSystem#45]
I'm not sure if this is know but I've noticed that there's a conflict with Mod conflict with Contractor mod. Removed all mods except Contractor mod, new save game with both mods, game has locked up.
[log.txt](https://github.com/stijnwop/manureSystem/files/4373593/log.txt)
![20200324165446_1](https://user-images.githubusercontent.com/48873188/77396938-65758280-6df0-11ea-8feb-35c4db91a537.jpg)
![20200324165448_1](https://user-images.githubusercontent.com/48873188/77396950-6c03fa00-6df0-11ea-9c57-e10d84874deb.jpg)

**Comment by Tankieboy** [comment]
Have you got the latest as I use Contractor mod and it works fine?

**Comment by AC2500S** [comment]
v1.0.0.7 is the lastest I can find and have

**Comment by stijnwop** [comment]
Update the manure system mod with the GitHub version, has been fixed weeks ago.

**Comment by stijnwop** [comment]
@AC2500S please test with the latest version.. and close the issue when solved.

**Comment by marmarino62** [comment]
Good morning I tried with the latest version fo manure system from 2 days ago and still the same problem. Can you please advise?

**Comment by stijnwop** [comment]
Don't think you updated then.. I can't reproduce it anymore and fix seem to work yesterday.

**Comment by marmarino62** [comment]
I did downloaded the manure system master. Should I replace this version with the one I had of the original manure system 1.0?
